CREATE TABLE HDL_Project.`MVI_MICE_sima_rh` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` FLOAT NULL
, `SO` FLOAT NULL
, `NO2` FLOAT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` FLOAT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` FLOAT NULL
, `NTE2` FLOAT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_MICE_SIMA_Data/MVI_MICE_sima_rh.csv"
;
CREATE TABLE HDL_Project.`MVI_MICE_sima_pm10` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` FLOAT NULL
, `SO` FLOAT NULL
, `NO2` FLOAT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` FLOAT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` FLOAT NULL
, `NTE2` FLOAT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_MICE_SIMA_Data/MVI_MICE_sima_pm10.csv"
;
CREATE TABLE HDL_Project.`MVI_MICE_sima_nox` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` FLOAT NULL
, `SO` FLOAT NULL
, `NO2` FLOAT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` FLOAT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` FLOAT NULL
, `NTE2` FLOAT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_MICE_SIMA_Data/MVI_MICE_sima_nox.csv"
;
CREATE TABLE HDL_Project.`MVI_MICE_sima_wsr` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` FLOAT NULL
, `SO` FLOAT NULL
, `NO2` FLOAT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` FLOAT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` FLOAT NULL
, `NTE2` FLOAT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_MICE_SIMA_Data/MVI_MICE_sima_wsr.csv"
;
CREATE TABLE HDL_Project.`MVI_MICE_sima_o3` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` FLOAT NULL
, `SO` FLOAT NULL
, `NO2` FLOAT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` FLOAT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` FLOAT NULL
, `NTE2` FLOAT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_MICE_SIMA_Data/MVI_MICE_sima_o3.csv"
;
CREATE TABLE HDL_Project.`MVI_MICE_sima_wdr` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` FLOAT NULL
, `SO` FLOAT NULL
, `NO2` FLOAT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` FLOAT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` FLOAT NULL
, `NTE2` FLOAT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_MICE_SIMA_Data/MVI_MICE_sima_wdr.csv"
;
CREATE TABLE HDL_Project.`MVI_MICE_sima_prs` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` FLOAT NULL
, `SO` FLOAT NULL
, `NO2` FLOAT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` FLOAT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` FLOAT NULL
, `NTE2` FLOAT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_MICE_SIMA_Data/MVI_MICE_sima_prs.csv"
;
CREATE TABLE HDL_Project.`MVI_MICE_sima_rainf` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` FLOAT NULL
, `SO` FLOAT NULL
, `NO2` FLOAT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` FLOAT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` FLOAT NULL
, `NTE2` FLOAT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_MICE_SIMA_Data/MVI_MICE_sima_rainf.csv"
;
CREATE TABLE HDL_Project.`MVI_MICE_sima_no` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` FLOAT NULL
, `SO` FLOAT NULL
, `NO2` FLOAT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` FLOAT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` FLOAT NULL
, `NTE2` FLOAT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_MICE_SIMA_Data/MVI_MICE_sima_no.csv"
;
CREATE TABLE HDL_Project.`MVI_MICE_sima_tout` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` FLOAT NULL
, `SO` FLOAT NULL
, `NO2` FLOAT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` FLOAT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` FLOAT NULL
, `NTE2` FLOAT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_MICE_SIMA_Data/MVI_MICE_sima_tout.csv"
;
CREATE TABLE HDL_Project.`MVI_MICE_sima_pm25` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` FLOAT NULL
, `SO` FLOAT NULL
, `NO2` FLOAT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` FLOAT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` FLOAT NULL
, `NTE2` FLOAT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_MICE_SIMA_Data/MVI_MICE_sima_pm25.csv"
;
CREATE TABLE HDL_Project.`MVI_MICE_sima_so2` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` FLOAT NULL
, `SO` FLOAT NULL
, `NO2` FLOAT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` FLOAT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` FLOAT NULL
, `NTE2` FLOAT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_MICE_SIMA_Data/MVI_MICE_sima_so2.csv"
;
CREATE TABLE HDL_Project.`MVI_MICE_sima_no2` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` FLOAT NULL
, `SO` FLOAT NULL
, `NO2` FLOAT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` FLOAT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` FLOAT NULL
, `NTE2` FLOAT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_MICE_SIMA_Data/MVI_MICE_sima_no2.csv"
;
CREATE TABLE HDL_Project.`MVI_MICE_sima_sr` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` FLOAT NULL
, `SO` FLOAT NULL
, `NO2` FLOAT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` FLOAT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` FLOAT NULL
, `NTE2` FLOAT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_MICE_SIMA_Data/MVI_MICE_sima_sr.csv"
;
CREATE TABLE HDL_Project.`MVI_MICE_sima_co` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` FLOAT NULL
, `SO` FLOAT NULL
, `NO2` FLOAT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` FLOAT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` FLOAT NULL
, `NTE2` FLOAT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_MICE_SIMA_Data/MVI_MICE_sima_co.csv"
;
