CREATE VIEW HDL_Project.sima_station_MVI_spatialAvg_SE AS 
Select l0.datetime, l0.CE as co, l1.SE as wsr, l2.SE as rh, l3.SE as pm25, l4.SE as rainf, l5.SE as nox, l6.SE as prs, l7.SE as no2, l8.SE as sr, l9.SE as wdr, l10.SE as so2, l11.SE as tout, l12.SE as no, l13.SE as pm10
from HDL_Project.MVI_spatialAvg_sima_o3 l0  left join HDL_Project.MVI_spatialAvg_sima_wsr l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_spatialAvg_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_spatialAvg_sima_pm25 l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_spatialAvg_sima_rainf l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_spatialAvg_sima_co l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_spatialAvg_sima_nox l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_spatialAvg_sima_prs l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_spatialAvg_sima_no2 l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_spatialAvg_sima_sr l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_spatialAvg_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_spatialAvg_sima_so2 l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_spatialAvg_sima_tout l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_spatialAvg_sima_no l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_spatialAvg_NE AS 
Select l0.datetime, l0.CE as co, l1.NE as wsr, l2.NE as rh, l3.NE as pm25, l4.NE as rainf, l5.NE as nox, l6.NE as prs, l7.NE as no2, l8.NE as sr, l9.NE as wdr, l10.NE as so2, l11.NE as tout, l12.NE as no, l13.NE as pm10
from HDL_Project.MVI_spatialAvg_sima_o3 l0  left join HDL_Project.MVI_spatialAvg_sima_wsr l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_spatialAvg_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_spatialAvg_sima_pm25 l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_spatialAvg_sima_rainf l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_spatialAvg_sima_co l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_spatialAvg_sima_nox l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_spatialAvg_sima_prs l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_spatialAvg_sima_no2 l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_spatialAvg_sima_sr l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_spatialAvg_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_spatialAvg_sima_so2 l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_spatialAvg_sima_tout l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_spatialAvg_sima_no l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_spatialAvg_CE AS 
Select l0.datetime, l0.CE as co, l1.CE as wsr, l2.CE as rh, l3.CE as pm25, l4.CE as rainf, l5.CE as nox, l6.CE as prs, l7.CE as no2, l8.CE as sr, l9.CE as wdr, l10.CE as so2, l11.CE as tout, l12.CE as no, l13.CE as pm10
from HDL_Project.MVI_spatialAvg_sima_o3 l0  left join HDL_Project.MVI_spatialAvg_sima_wsr l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_spatialAvg_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_spatialAvg_sima_pm25 l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_spatialAvg_sima_rainf l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_spatialAvg_sima_co l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_spatialAvg_sima_nox l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_spatialAvg_sima_prs l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_spatialAvg_sima_no2 l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_spatialAvg_sima_sr l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_spatialAvg_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_spatialAvg_sima_so2 l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_spatialAvg_sima_tout l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_spatialAvg_sima_no l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_spatialAvg_NO AS 
Select l0.datetime, l0.CE as co, l1.NO as wsr, l2.NO as rh, l3.NO as pm25, l4.NO as rainf, l5.NO as nox, l6.NO as prs, l7.NO as no2, l8.NO as sr, l9.NO as wdr, l10.NO as so2, l11.NO as tout, l12.NO as no, l13.NO as pm10
from HDL_Project.MVI_spatialAvg_sima_o3 l0  left join HDL_Project.MVI_spatialAvg_sima_wsr l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_spatialAvg_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_spatialAvg_sima_pm25 l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_spatialAvg_sima_rainf l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_spatialAvg_sima_co l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_spatialAvg_sima_nox l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_spatialAvg_sima_prs l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_spatialAvg_sima_no2 l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_spatialAvg_sima_sr l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_spatialAvg_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_spatialAvg_sima_so2 l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_spatialAvg_sima_tout l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_spatialAvg_sima_no l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_spatialAvg_SO AS 
Select l0.datetime, l0.CE as co, l1.SO as wsr, l2.SO as rh, l3.SO as pm25, l4.SO as rainf, l5.SO as nox, l6.SO as prs, l7.SO as no2, l8.SO as sr, l9.SO as wdr, l10.SO as so2, l11.SO as tout, l12.SO as no, l13.SO as pm10
from HDL_Project.MVI_spatialAvg_sima_o3 l0  left join HDL_Project.MVI_spatialAvg_sima_wsr l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_spatialAvg_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_spatialAvg_sima_pm25 l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_spatialAvg_sima_rainf l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_spatialAvg_sima_co l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_spatialAvg_sima_nox l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_spatialAvg_sima_prs l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_spatialAvg_sima_no2 l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_spatialAvg_sima_sr l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_spatialAvg_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_spatialAvg_sima_so2 l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_spatialAvg_sima_tout l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_spatialAvg_sima_no l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_spatialAvg_NO2 AS 
Select l0.datetime, l0.CE as co, l1.NO2 as wsr, l2.NO2 as rh, l3.NO2 as pm25, l4.NO2 as rainf, l5.NO2 as nox, l6.NO2 as prs, l7.NO2 as no2, l8.NO2 as sr, l9.NO2 as wdr, l10.NO2 as so2, l11.NO2 as tout, l12.NO2 as no, l13.NO2 as pm10
from HDL_Project.MVI_spatialAvg_sima_o3 l0  left join HDL_Project.MVI_spatialAvg_sima_wsr l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_spatialAvg_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_spatialAvg_sima_pm25 l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_spatialAvg_sima_rainf l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_spatialAvg_sima_co l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_spatialAvg_sima_nox l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_spatialAvg_sima_prs l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_spatialAvg_sima_no2 l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_spatialAvg_sima_sr l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_spatialAvg_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_spatialAvg_sima_so2 l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_spatialAvg_sima_tout l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_spatialAvg_sima_no l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_spatialAvg_NTE AS 
Select l0.datetime, l0.CE as co, l1.NTE as wsr, l2.NTE as rh, l3.NTE as pm25, l4.NTE as rainf, l5.NTE as nox, l6.NTE as prs, l7.NTE as no2, l8.NTE as sr, l9.NTE as wdr, l10.NTE as so2, l11.NTE as tout, l12.NTE as no, l13.NTE as pm10
from HDL_Project.MVI_spatialAvg_sima_o3 l0  left join HDL_Project.MVI_spatialAvg_sima_wsr l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_spatialAvg_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_spatialAvg_sima_pm25 l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_spatialAvg_sima_rainf l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_spatialAvg_sima_co l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_spatialAvg_sima_nox l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_spatialAvg_sima_prs l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_spatialAvg_sima_no2 l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_spatialAvg_sima_sr l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_spatialAvg_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_spatialAvg_sima_so2 l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_spatialAvg_sima_tout l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_spatialAvg_sima_no l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_spatialAvg_NE2 AS 
Select l0.datetime, l0.CE as co, l1.NE2 as wsr, l2.NE2 as rh, l3.NE2 as pm25, l4.NE2 as rainf, l5.NE2 as nox, l6.NE2 as prs, l7.NE2 as no2, l8.NE2 as sr, l9.NE2 as wdr, l10.NE2 as so2, l11.NE2 as tout, l12.NE2 as no, l13.NE2 as pm10
from HDL_Project.MVI_spatialAvg_sima_o3 l0  left join HDL_Project.MVI_spatialAvg_sima_wsr l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_spatialAvg_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_spatialAvg_sima_pm25 l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_spatialAvg_sima_rainf l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_spatialAvg_sima_co l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_spatialAvg_sima_nox l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_spatialAvg_sima_prs l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_spatialAvg_sima_no2 l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_spatialAvg_sima_sr l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_spatialAvg_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_spatialAvg_sima_so2 l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_spatialAvg_sima_tout l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_spatialAvg_sima_no l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_spatialAvg_SE2 AS 
Select l0.datetime, l0.CE as co, l1.SE2 as wsr, l2.SE2 as rh, l3.SE2 as pm25, l4.SE2 as rainf, l5.SE2 as nox, l6.SE2 as prs, l7.SE2 as no2, l8.SE2 as sr, l9.SE2 as wdr, l10.SE2 as so2, l11.SE2 as tout, l12.SE2 as no, l13.SE2 as pm10
from HDL_Project.MVI_spatialAvg_sima_o3 l0  left join HDL_Project.MVI_spatialAvg_sima_wsr l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_spatialAvg_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_spatialAvg_sima_pm25 l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_spatialAvg_sima_rainf l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_spatialAvg_sima_co l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_spatialAvg_sima_nox l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_spatialAvg_sima_prs l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_spatialAvg_sima_no2 l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_spatialAvg_sima_sr l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_spatialAvg_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_spatialAvg_sima_so2 l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_spatialAvg_sima_tout l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_spatialAvg_sima_no l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_spatialAvg_SO2 AS 
Select l0.datetime, l0.CE as co, l1.SO2 as wsr, l2.SO2 as rh, l3.SO2 as pm25, l4.SO2 as rainf, l5.SO2 as nox, l6.SO2 as prs, l7.SO2 as no2, l8.SO2 as sr, l9.SO2 as wdr, l10.SO2 as so2, l11.SO2 as tout, l12.SO2 as no, l13.SO2 as pm10
from HDL_Project.MVI_spatialAvg_sima_o3 l0  left join HDL_Project.MVI_spatialAvg_sima_wsr l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_spatialAvg_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_spatialAvg_sima_pm25 l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_spatialAvg_sima_rainf l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_spatialAvg_sima_co l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_spatialAvg_sima_nox l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_spatialAvg_sima_prs l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_spatialAvg_sima_no2 l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_spatialAvg_sima_sr l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_spatialAvg_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_spatialAvg_sima_so2 l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_spatialAvg_sima_tout l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_spatialAvg_sima_no l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_spatialAvg_SE3 AS 
Select l0.datetime, l0.CE as co, l1.SE3 as wsr, l2.SE3 as rh, l3.SE3 as pm25, l4.SE3 as rainf, l5.SE3 as nox, l6.SE3 as prs, l7.SE3 as no2, l8.SE3 as sr, l9.SE3 as wdr, l10.SE3 as so2, l11.SE3 as tout, l12.SE3 as no, l13.SE3 as pm10
from HDL_Project.MVI_spatialAvg_sima_o3 l0  left join HDL_Project.MVI_spatialAvg_sima_wsr l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_spatialAvg_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_spatialAvg_sima_pm25 l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_spatialAvg_sima_rainf l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_spatialAvg_sima_co l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_spatialAvg_sima_nox l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_spatialAvg_sima_prs l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_spatialAvg_sima_no2 l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_spatialAvg_sima_sr l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_spatialAvg_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_spatialAvg_sima_so2 l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_spatialAvg_sima_tout l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_spatialAvg_sima_no l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_spatialAvg_SUR AS 
Select l0.datetime, l0.CE as co, l1.SUR as wsr, l2.SUR as rh, l3.SUR as pm25, l4.SUR as rainf, l5.SUR as nox, l6.SUR as prs, l7.SUR as no2, l8.SUR as sr, l9.SUR as wdr, l10.SUR as so2, l11.SUR as tout, l12.SUR as no, l13.SUR as pm10
from HDL_Project.MVI_spatialAvg_sima_o3 l0  left join HDL_Project.MVI_spatialAvg_sima_wsr l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_spatialAvg_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_spatialAvg_sima_pm25 l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_spatialAvg_sima_rainf l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_spatialAvg_sima_co l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_spatialAvg_sima_nox l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_spatialAvg_sima_prs l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_spatialAvg_sima_no2 l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_spatialAvg_sima_sr l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_spatialAvg_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_spatialAvg_sima_so2 l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_spatialAvg_sima_tout l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_spatialAvg_sima_no l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_spatialAvg_NTE2 AS 
Select l0.datetime, l0.CE as co, l1.NTE2 as wsr, l2.NTE2 as rh, l3.NTE2 as pm25, l4.NTE2 as rainf, l5.NTE2 as nox, l6.NTE2 as prs, l7.NTE2 as no2, l8.NTE2 as sr, l9.NTE2 as wdr, l10.NTE2 as so2, l11.NTE2 as tout, l12.NTE2 as no, l13.NTE2 as pm10
from HDL_Project.MVI_spatialAvg_sima_o3 l0  left join HDL_Project.MVI_spatialAvg_sima_wsr l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_spatialAvg_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_spatialAvg_sima_pm25 l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_spatialAvg_sima_rainf l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_spatialAvg_sima_co l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_spatialAvg_sima_nox l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_spatialAvg_sima_prs l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_spatialAvg_sima_no2 l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_spatialAvg_sima_sr l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_spatialAvg_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_spatialAvg_sima_so2 l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_spatialAvg_sima_tout l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_spatialAvg_sima_no l13 ON l0.datetime = l13.datetime;

