CREATE VIEW HDL_Project.sima_station_MVI_mean_SE AS 
Select l0.datetime, l0.CE as co, l1.SE as no, l2.SE as rh, l3.SE as tout, l4.SE as no2, l5.SE as sr, l6.SE as o3, l7.SE as nox, l8.SE as rainf, l9.SE as pm10, l10.SE as wdr, l11.SE as pm25, l12.SE as wsr, l13.SE as so2
from HDL_Project.MVI_mean_sima_prs l0  left join HDL_Project.MVI_mean_sima_no l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_mean_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_mean_sima_tout l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_mean_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_mean_sima_sr l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_mean_sima_o3 l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_mean_sima_nox l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_mean_sima_rainf l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_mean_sima_pm10 l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_mean_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_mean_sima_co l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_mean_sima_pm25 l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_mean_sima_wsr l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_mean_NE AS 
Select l0.datetime, l0.CE as co, l1.NE as no, l2.NE as rh, l3.NE as tout, l4.NE as no2, l5.NE as sr, l6.NE as o3, l7.NE as nox, l8.NE as rainf, l9.NE as pm10, l10.NE as wdr, l11.NE as pm25, l12.NE as wsr, l13.NE as so2
from HDL_Project.MVI_mean_sima_prs l0  left join HDL_Project.MVI_mean_sima_no l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_mean_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_mean_sima_tout l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_mean_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_mean_sima_sr l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_mean_sima_o3 l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_mean_sima_nox l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_mean_sima_rainf l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_mean_sima_pm10 l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_mean_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_mean_sima_co l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_mean_sima_pm25 l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_mean_sima_wsr l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_mean_CE AS 
Select l0.datetime, l0.CE as co, l1.CE as no, l2.CE as rh, l3.CE as tout, l4.CE as no2, l5.CE as sr, l6.CE as o3, l7.CE as nox, l8.CE as rainf, l9.CE as pm10, l10.CE as wdr, l11.CE as pm25, l12.CE as wsr, l13.CE as so2
from HDL_Project.MVI_mean_sima_prs l0  left join HDL_Project.MVI_mean_sima_no l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_mean_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_mean_sima_tout l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_mean_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_mean_sima_sr l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_mean_sima_o3 l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_mean_sima_nox l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_mean_sima_rainf l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_mean_sima_pm10 l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_mean_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_mean_sima_co l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_mean_sima_pm25 l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_mean_sima_wsr l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_mean_NO AS 
Select l0.datetime, l0.CE as co, l1.NO as no, l2.NO as rh, l3.NO as tout, l4.NO as no2, l5.NO as sr, l6.NO as o3, l7.NO as nox, l8.NO as rainf, l9.NO as pm10, l10.NO as wdr, l11.NO as pm25, l12.NO as wsr, l13.NO as so2
from HDL_Project.MVI_mean_sima_prs l0  left join HDL_Project.MVI_mean_sima_no l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_mean_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_mean_sima_tout l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_mean_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_mean_sima_sr l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_mean_sima_o3 l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_mean_sima_nox l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_mean_sima_rainf l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_mean_sima_pm10 l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_mean_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_mean_sima_co l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_mean_sima_pm25 l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_mean_sima_wsr l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_mean_SO AS 
Select l0.datetime, l0.CE as co, l1.SO as no, l2.SO as rh, l3.SO as tout, l4.SO as no2, l5.SO as sr, l6.SO as o3, l7.SO as nox, l8.SO as rainf, l9.SO as pm10, l10.SO as wdr, l11.SO as pm25, l12.SO as wsr, l13.SO as so2
from HDL_Project.MVI_mean_sima_prs l0  left join HDL_Project.MVI_mean_sima_no l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_mean_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_mean_sima_tout l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_mean_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_mean_sima_sr l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_mean_sima_o3 l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_mean_sima_nox l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_mean_sima_rainf l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_mean_sima_pm10 l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_mean_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_mean_sima_co l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_mean_sima_pm25 l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_mean_sima_wsr l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_mean_NO2 AS 
Select l0.datetime, l0.CE as co, l1.NO2 as no, l2.NO2 as rh, l3.NO2 as tout, l4.NO2 as no2, l5.NO2 as sr, l6.NO2 as o3, l7.NO2 as nox, l8.NO2 as rainf, l9.NO2 as pm10, l10.NO2 as wdr, l11.NO2 as pm25, l12.NO2 as wsr, l13.NO2 as so2
from HDL_Project.MVI_mean_sima_prs l0  left join HDL_Project.MVI_mean_sima_no l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_mean_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_mean_sima_tout l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_mean_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_mean_sima_sr l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_mean_sima_o3 l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_mean_sima_nox l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_mean_sima_rainf l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_mean_sima_pm10 l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_mean_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_mean_sima_co l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_mean_sima_pm25 l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_mean_sima_wsr l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_mean_NTE AS 
Select l0.datetime, l0.CE as co, l1.NTE as no, l2.NTE as rh, l3.NTE as tout, l4.NTE as no2, l5.NTE as sr, l6.NTE as o3, l7.NTE as nox, l8.NTE as rainf, l9.NTE as pm10, l10.NTE as wdr, l11.NTE as pm25, l12.NTE as wsr, l13.NTE as so2
from HDL_Project.MVI_mean_sima_prs l0  left join HDL_Project.MVI_mean_sima_no l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_mean_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_mean_sima_tout l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_mean_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_mean_sima_sr l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_mean_sima_o3 l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_mean_sima_nox l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_mean_sima_rainf l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_mean_sima_pm10 l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_mean_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_mean_sima_co l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_mean_sima_pm25 l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_mean_sima_wsr l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_mean_NE2 AS 
Select l0.datetime, l0.CE as co, l1.NE2 as no, l2.NE2 as rh, l3.NE2 as tout, l4.NE2 as no2, l5.NE2 as sr, l6.NE2 as o3, l7.NE2 as nox, l8.NE2 as rainf, l9.NE2 as pm10, l10.NE2 as wdr, l11.NE2 as pm25, l12.NE2 as wsr, l13.NE2 as so2
from HDL_Project.MVI_mean_sima_prs l0  left join HDL_Project.MVI_mean_sima_no l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_mean_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_mean_sima_tout l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_mean_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_mean_sima_sr l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_mean_sima_o3 l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_mean_sima_nox l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_mean_sima_rainf l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_mean_sima_pm10 l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_mean_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_mean_sima_co l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_mean_sima_pm25 l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_mean_sima_wsr l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_mean_SE2 AS 
Select l0.datetime, l0.CE as co, l1.SE2 as no, l2.SE2 as rh, l3.SE2 as tout, l4.SE2 as no2, l5.SE2 as sr, l6.SE2 as o3, l7.SE2 as nox, l8.SE2 as rainf, l9.SE2 as pm10, l10.SE2 as wdr, l11.SE2 as pm25, l12.SE2 as wsr, l13.SE2 as so2
from HDL_Project.MVI_mean_sima_prs l0  left join HDL_Project.MVI_mean_sima_no l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_mean_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_mean_sima_tout l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_mean_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_mean_sima_sr l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_mean_sima_o3 l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_mean_sima_nox l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_mean_sima_rainf l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_mean_sima_pm10 l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_mean_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_mean_sima_co l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_mean_sima_pm25 l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_mean_sima_wsr l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_mean_SO2 AS 
Select l0.datetime, l0.CE as co, l1.SO2 as no, l2.SO2 as rh, l3.SO2 as tout, l4.SO2 as no2, l5.SO2 as sr, l6.SO2 as o3, l7.SO2 as nox, l8.SO2 as rainf, l9.SO2 as pm10, l10.SO2 as wdr, l11.SO2 as pm25, l12.SO2 as wsr, l13.SO2 as so2
from HDL_Project.MVI_mean_sima_prs l0  left join HDL_Project.MVI_mean_sima_no l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_mean_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_mean_sima_tout l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_mean_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_mean_sima_sr l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_mean_sima_o3 l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_mean_sima_nox l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_mean_sima_rainf l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_mean_sima_pm10 l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_mean_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_mean_sima_co l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_mean_sima_pm25 l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_mean_sima_wsr l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_mean_SE3 AS 
Select l0.datetime, l0.CE as co, l1.SE3 as no, l2.SE3 as rh, l3.SE3 as tout, l4.SE3 as no2, l5.SE3 as sr, l6.SE3 as o3, l7.SE3 as nox, l8.SE3 as rainf, l9.SE3 as pm10, l10.SE3 as wdr, l11.SE3 as pm25, l12.SE3 as wsr, l13.SE3 as so2
from HDL_Project.MVI_mean_sima_prs l0  left join HDL_Project.MVI_mean_sima_no l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_mean_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_mean_sima_tout l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_mean_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_mean_sima_sr l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_mean_sima_o3 l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_mean_sima_nox l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_mean_sima_rainf l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_mean_sima_pm10 l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_mean_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_mean_sima_co l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_mean_sima_pm25 l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_mean_sima_wsr l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_mean_SUR AS 
Select l0.datetime, l0.CE as co, l1.SUR as no, l2.SUR as rh, l3.SUR as tout, l4.SUR as no2, l5.SUR as sr, l6.SUR as o3, l7.SUR as nox, l8.SUR as rainf, l9.SUR as pm10, l10.SUR as wdr, l11.SUR as pm25, l12.SUR as wsr, l13.SUR as so2
from HDL_Project.MVI_mean_sima_prs l0  left join HDL_Project.MVI_mean_sima_no l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_mean_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_mean_sima_tout l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_mean_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_mean_sima_sr l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_mean_sima_o3 l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_mean_sima_nox l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_mean_sima_rainf l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_mean_sima_pm10 l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_mean_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_mean_sima_co l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_mean_sima_pm25 l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_mean_sima_wsr l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_mean_NTE2 AS 
Select l0.datetime, l0.CE as co, l1.NTE2 as no, l2.NTE2 as rh, l3.NTE2 as tout, l4.NTE2 as no2, l5.NTE2 as sr, l6.NTE2 as o3, l7.NTE2 as nox, l8.NTE2 as rainf, l9.NTE2 as pm10, l10.NTE2 as wdr, l11.NTE2 as pm25, l12.NTE2 as wsr, l13.NTE2 as so2
from HDL_Project.MVI_mean_sima_prs l0  left join HDL_Project.MVI_mean_sima_no l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_mean_sima_rh l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_mean_sima_tout l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_mean_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_mean_sima_sr l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_mean_sima_o3 l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_mean_sima_nox l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_mean_sima_rainf l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_mean_sima_pm10 l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_mean_sima_wdr l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_mean_sima_co l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_mean_sima_pm25 l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_mean_sima_wsr l13 ON l0.datetime = l13.datetime;

