#!/bin/bash
mysql -ucesar -pmysql92@ --local-infile HDL_Project -e "LOAD DATA LOCAL INFILE './MVI_spatialAvg_SIMA_Data/MVI_spatialAvg_sima_o3.csv'  INTO TABLE MVI_spatialAvg_sima_o3 FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 ROWS"; 
mysql -ucesar -pmysql92@ --local-infile HDL_Project -e "LOAD DATA LOCAL INFILE './MVI_spatialAvg_SIMA_Data/MVI_spatialAvg_sima_wsr.csv'  INTO TABLE MVI_spatialAvg_sima_wsr FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 ROWS"; 
mysql -ucesar -pmysql92@ --local-infile HDL_Project -e "LOAD DATA LOCAL INFILE './MVI_spatialAvg_SIMA_Data/MVI_spatialAvg_sima_rh.csv'  INTO TABLE MVI_spatialAvg_sima_rh FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 ROWS"; 
mysql -ucesar -pmysql92@ --local-infile HDL_Project -e "LOAD DATA LOCAL INFILE './MVI_spatialAvg_SIMA_Data/MVI_spatialAvg_sima_pm25.csv'  INTO TABLE MVI_spatialAvg_sima_pm25 FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 ROWS"; 
mysql -ucesar -pmysql92@ --local-infile HDL_Project -e "LOAD DATA LOCAL INFILE './MVI_spatialAvg_SIMA_Data/MVI_spatialAvg_sima_rainf.csv'  INTO TABLE MVI_spatialAvg_sima_rainf FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 ROWS"; 
mysql -ucesar -pmysql92@ --local-infile HDL_Project -e "LOAD DATA LOCAL INFILE './MVI_spatialAvg_SIMA_Data/MVI_spatialAvg_sima_co.csv'  INTO TABLE MVI_spatialAvg_sima_co FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 ROWS"; 
mysql -ucesar -pmysql92@ --local-infile HDL_Project -e "LOAD DATA LOCAL INFILE './MVI_spatialAvg_SIMA_Data/MVI_spatialAvg_sima_nox.csv'  INTO TABLE MVI_spatialAvg_sima_nox FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 ROWS"; 
mysql -ucesar -pmysql92@ --local-infile HDL_Project -e "LOAD DATA LOCAL INFILE './MVI_spatialAvg_SIMA_Data/MVI_spatialAvg_sima_prs.csv'  INTO TABLE MVI_spatialAvg_sima_prs FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 ROWS"; 
mysql -ucesar -pmysql92@ --local-infile HDL_Project -e "LOAD DATA LOCAL INFILE './MVI_spatialAvg_SIMA_Data/MVI_spatialAvg_sima_no2.csv'  INTO TABLE MVI_spatialAvg_sima_no2 FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 ROWS"; 
mysql -ucesar -pmysql92@ --local-infile HDL_Project -e "LOAD DATA LOCAL INFILE './MVI_spatialAvg_SIMA_Data/MVI_spatialAvg_sima_sr.csv'  INTO TABLE MVI_spatialAvg_sima_sr FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 ROWS"; 
mysql -ucesar -pmysql92@ --local-infile HDL_Project -e "LOAD DATA LOCAL INFILE './MVI_spatialAvg_SIMA_Data/MVI_spatialAvg_sima_wdr.csv'  INTO TABLE MVI_spatialAvg_sima_wdr FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 ROWS"; 
mysql -ucesar -pmysql92@ --local-infile HDL_Project -e "LOAD DATA LOCAL INFILE './MVI_spatialAvg_SIMA_Data/MVI_spatialAvg_sima_so2.csv'  INTO TABLE MVI_spatialAvg_sima_so2 FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 ROWS"; 
mysql -ucesar -pmysql92@ --local-infile HDL_Project -e "LOAD DATA LOCAL INFILE './MVI_spatialAvg_SIMA_Data/MVI_spatialAvg_sima_tout.csv'  INTO TABLE MVI_spatialAvg_sima_tout FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 ROWS"; 
mysql -ucesar -pmysql92@ --local-infile HDL_Project -e "LOAD DATA LOCAL INFILE './MVI_spatialAvg_SIMA_Data/MVI_spatialAvg_sima_no.csv'  INTO TABLE MVI_spatialAvg_sima_no FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 ROWS"; 
mysql -ucesar -pmysql92@ --local-infile HDL_Project -e "LOAD DATA LOCAL INFILE './MVI_spatialAvg_SIMA_Data/MVI_spatialAvg_sima_pm10.csv'  INTO TABLE MVI_spatialAvg_sima_pm10 FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 ROWS"; 
