CREATE TABLE HDL_Project.`MVI_mean_sima_prs` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_mean_SIMA_Data/MVI_mean_sima_prs.csv"
;
CREATE TABLE HDL_Project.`MVI_mean_sima_no` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_mean_SIMA_Data/MVI_mean_sima_no.csv"
;
CREATE TABLE HDL_Project.`MVI_mean_sima_rh` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_mean_SIMA_Data/MVI_mean_sima_rh.csv"
;
CREATE TABLE HDL_Project.`MVI_mean_sima_tout` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_mean_SIMA_Data/MVI_mean_sima_tout.csv"
;
CREATE TABLE HDL_Project.`MVI_mean_sima_no2` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_mean_SIMA_Data/MVI_mean_sima_no2.csv"
;
CREATE TABLE HDL_Project.`MVI_mean_sima_sr` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_mean_SIMA_Data/MVI_mean_sima_sr.csv"
;
CREATE TABLE HDL_Project.`MVI_mean_sima_o3` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_mean_SIMA_Data/MVI_mean_sima_o3.csv"
;
CREATE TABLE HDL_Project.`MVI_mean_sima_nox` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_mean_SIMA_Data/MVI_mean_sima_nox.csv"
;
CREATE TABLE HDL_Project.`MVI_mean_sima_rainf` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_mean_SIMA_Data/MVI_mean_sima_rainf.csv"
;
CREATE TABLE HDL_Project.`MVI_mean_sima_pm10` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_mean_SIMA_Data/MVI_mean_sima_pm10.csv"
;
CREATE TABLE HDL_Project.`MVI_mean_sima_wdr` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_mean_SIMA_Data/MVI_mean_sima_wdr.csv"
;
CREATE TABLE HDL_Project.`MVI_mean_sima_co` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_mean_SIMA_Data/MVI_mean_sima_co.csv"
;
CREATE TABLE HDL_Project.`MVI_mean_sima_pm25` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_mean_SIMA_Data/MVI_mean_sima_pm25.csv"
;
CREATE TABLE HDL_Project.`MVI_mean_sima_wsr` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_mean_SIMA_Data/MVI_mean_sima_wsr.csv"
;
CREATE TABLE HDL_Project.`MVI_mean_sima_so2` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: ./MVI_mean_SIMA_Data/MVI_mean_sima_so2.csv"
;
