CREATE VIEW HDL_Project.sima_station_MVI_MICE_SE AS 
Select l0.datetime, l0.CE as co, l1.SE as tout, l2.SE as no, l3.SE as sr, l4.SE as no2, l5.SE as pm25, l6.SE as wsr, l7.SE as o3, l8.SE as wdr, l9.SE as rainf, l10.SE as pm10, l11.SE as nox, l12.SE as prs, l13.SE as so2
from HDL_Project.MVI_MICE_sima_rh l0  left join HDL_Project.MVI_MICE_sima_tout l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_MICE_sima_no l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_MICE_sima_sr l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_MICE_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_MICE_sima_pm25 l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_MICE_sima_wsr l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_MICE_sima_o3 l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_MICE_sima_wdr l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_MICE_sima_rainf l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_MICE_sima_pm10 l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_MICE_sima_nox l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_MICE_sima_prs l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_MICE_sima_so2 l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_MICE_NE AS 
Select l0.datetime, l0.CE as co, l1.NE as tout, l2.NE as no, l3.NE as sr, l4.NE as no2, l5.NE as pm25, l6.NE as wsr, l7.NE as o3, l8.NE as wdr, l9.NE as rainf, l10.NE as pm10, l11.NE as nox, l12.NE as prs, l13.NE as so2
from HDL_Project.MVI_MICE_sima_rh l0  left join HDL_Project.MVI_MICE_sima_tout l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_MICE_sima_no l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_MICE_sima_sr l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_MICE_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_MICE_sima_pm25 l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_MICE_sima_wsr l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_MICE_sima_o3 l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_MICE_sima_wdr l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_MICE_sima_rainf l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_MICE_sima_pm10 l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_MICE_sima_nox l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_MICE_sima_prs l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_MICE_sima_so2 l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_MICE_CE AS 
Select l0.datetime, l0.CE as co, l1.CE as tout, l2.CE as no, l3.CE as sr, l4.CE as no2, l5.CE as pm25, l6.CE as wsr, l7.CE as o3, l8.CE as wdr, l9.CE as rainf, l10.CE as pm10, l11.CE as nox, l12.CE as prs, l13.CE as so2
from HDL_Project.MVI_MICE_sima_rh l0  left join HDL_Project.MVI_MICE_sima_tout l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_MICE_sima_no l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_MICE_sima_sr l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_MICE_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_MICE_sima_pm25 l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_MICE_sima_wsr l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_MICE_sima_o3 l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_MICE_sima_wdr l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_MICE_sima_rainf l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_MICE_sima_pm10 l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_MICE_sima_nox l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_MICE_sima_prs l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_MICE_sima_so2 l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_MICE_NO AS 
Select l0.datetime, l0.CE as co, l1.NO as tout, l2.NO as no, l3.NO as sr, l4.NO as no2, l5.NO as pm25, l6.NO as wsr, l7.NO as o3, l8.NO as wdr, l9.NO as rainf, l10.NO as pm10, l11.NO as nox, l12.NO as prs, l13.NO as so2
from HDL_Project.MVI_MICE_sima_rh l0  left join HDL_Project.MVI_MICE_sima_tout l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_MICE_sima_no l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_MICE_sima_sr l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_MICE_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_MICE_sima_pm25 l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_MICE_sima_wsr l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_MICE_sima_o3 l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_MICE_sima_wdr l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_MICE_sima_rainf l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_MICE_sima_pm10 l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_MICE_sima_nox l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_MICE_sima_prs l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_MICE_sima_so2 l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_MICE_SO AS 
Select l0.datetime, l0.CE as co, l1.SO as tout, l2.SO as no, l3.SO as sr, l4.SO as no2, l5.SO as pm25, l6.SO as wsr, l7.SO as o3, l8.SO as wdr, l9.SO as rainf, l10.SO as pm10, l11.SO as nox, l12.SO as prs, l13.SO as so2
from HDL_Project.MVI_MICE_sima_rh l0  left join HDL_Project.MVI_MICE_sima_tout l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_MICE_sima_no l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_MICE_sima_sr l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_MICE_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_MICE_sima_pm25 l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_MICE_sima_wsr l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_MICE_sima_o3 l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_MICE_sima_wdr l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_MICE_sima_rainf l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_MICE_sima_pm10 l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_MICE_sima_nox l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_MICE_sima_prs l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_MICE_sima_so2 l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_MICE_NO2 AS 
Select l0.datetime, l0.CE as co, l1.NO2 as tout, l2.NO2 as no, l3.NO2 as sr, l4.NO2 as no2, l5.NO2 as pm25, l6.NO2 as wsr, l7.NO2 as o3, l8.NO2 as wdr, l9.NO2 as rainf, l10.NO2 as pm10, l11.NO2 as nox, l12.NO2 as prs, l13.NO2 as so2
from HDL_Project.MVI_MICE_sima_rh l0  left join HDL_Project.MVI_MICE_sima_tout l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_MICE_sima_no l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_MICE_sima_sr l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_MICE_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_MICE_sima_pm25 l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_MICE_sima_wsr l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_MICE_sima_o3 l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_MICE_sima_wdr l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_MICE_sima_rainf l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_MICE_sima_pm10 l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_MICE_sima_nox l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_MICE_sima_prs l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_MICE_sima_so2 l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_MICE_NTE AS 
Select l0.datetime, l0.CE as co, l1.NTE as tout, l2.NTE as no, l3.NTE as sr, l4.NTE as no2, l5.NTE as pm25, l6.NTE as wsr, l7.NTE as o3, l8.NTE as wdr, l9.NTE as rainf, l10.NTE as pm10, l11.NTE as nox, l12.NTE as prs, l13.NTE as so2
from HDL_Project.MVI_MICE_sima_rh l0  left join HDL_Project.MVI_MICE_sima_tout l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_MICE_sima_no l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_MICE_sima_sr l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_MICE_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_MICE_sima_pm25 l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_MICE_sima_wsr l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_MICE_sima_o3 l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_MICE_sima_wdr l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_MICE_sima_rainf l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_MICE_sima_pm10 l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_MICE_sima_nox l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_MICE_sima_prs l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_MICE_sima_so2 l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_MICE_NE2 AS 
Select l0.datetime, l0.CE as co, l1.NE2 as tout, l2.NE2 as no, l3.NE2 as sr, l4.NE2 as no2, l5.NE2 as pm25, l6.NE2 as wsr, l7.NE2 as o3, l8.NE2 as wdr, l9.NE2 as rainf, l10.NE2 as pm10, l11.NE2 as nox, l12.NE2 as prs, l13.NE2 as so2
from HDL_Project.MVI_MICE_sima_rh l0  left join HDL_Project.MVI_MICE_sima_tout l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_MICE_sima_no l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_MICE_sima_sr l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_MICE_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_MICE_sima_pm25 l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_MICE_sima_wsr l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_MICE_sima_o3 l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_MICE_sima_wdr l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_MICE_sima_rainf l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_MICE_sima_pm10 l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_MICE_sima_nox l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_MICE_sima_prs l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_MICE_sima_so2 l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_MICE_SE2 AS 
Select l0.datetime, l0.CE as co, l1.SE2 as tout, l2.SE2 as no, l3.SE2 as sr, l4.SE2 as no2, l5.SE2 as pm25, l6.SE2 as wsr, l7.SE2 as o3, l8.SE2 as wdr, l9.SE2 as rainf, l10.SE2 as pm10, l11.SE2 as nox, l12.SE2 as prs, l13.SE2 as so2
from HDL_Project.MVI_MICE_sima_rh l0  left join HDL_Project.MVI_MICE_sima_tout l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_MICE_sima_no l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_MICE_sima_sr l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_MICE_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_MICE_sima_pm25 l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_MICE_sima_wsr l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_MICE_sima_o3 l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_MICE_sima_wdr l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_MICE_sima_rainf l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_MICE_sima_pm10 l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_MICE_sima_nox l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_MICE_sima_prs l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_MICE_sima_so2 l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_MICE_SO2 AS 
Select l0.datetime, l0.CE as co, l1.SO2 as tout, l2.SO2 as no, l3.SO2 as sr, l4.SO2 as no2, l5.SO2 as pm25, l6.SO2 as wsr, l7.SO2 as o3, l8.SO2 as wdr, l9.SO2 as rainf, l10.SO2 as pm10, l11.SO2 as nox, l12.SO2 as prs, l13.SO2 as so2
from HDL_Project.MVI_MICE_sima_rh l0  left join HDL_Project.MVI_MICE_sima_tout l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_MICE_sima_no l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_MICE_sima_sr l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_MICE_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_MICE_sima_pm25 l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_MICE_sima_wsr l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_MICE_sima_o3 l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_MICE_sima_wdr l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_MICE_sima_rainf l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_MICE_sima_pm10 l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_MICE_sima_nox l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_MICE_sima_prs l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_MICE_sima_so2 l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_MICE_SE3 AS 
Select l0.datetime, l0.CE as co, l1.SE3 as tout, l2.SE3 as no, l3.SE3 as sr, l4.SE3 as no2, l5.SE3 as pm25, l6.SE3 as wsr, l7.SE3 as o3, l8.SE3 as wdr, l9.SE3 as rainf, l10.SE3 as pm10, l11.SE3 as nox, l12.SE3 as prs, l13.SE3 as so2
from HDL_Project.MVI_MICE_sima_rh l0  left join HDL_Project.MVI_MICE_sima_tout l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_MICE_sima_no l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_MICE_sima_sr l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_MICE_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_MICE_sima_pm25 l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_MICE_sima_wsr l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_MICE_sima_o3 l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_MICE_sima_wdr l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_MICE_sima_rainf l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_MICE_sima_pm10 l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_MICE_sima_nox l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_MICE_sima_prs l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_MICE_sima_so2 l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_MICE_SUR AS 
Select l0.datetime, l0.CE as co, l1.SUR as tout, l2.SUR as no, l3.SUR as sr, l4.SUR as no2, l5.SUR as pm25, l6.SUR as wsr, l7.SUR as o3, l8.SUR as wdr, l9.SUR as rainf, l10.SUR as pm10, l11.SUR as nox, l12.SUR as prs, l13.SUR as so2
from HDL_Project.MVI_MICE_sima_rh l0  left join HDL_Project.MVI_MICE_sima_tout l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_MICE_sima_no l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_MICE_sima_sr l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_MICE_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_MICE_sima_pm25 l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_MICE_sima_wsr l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_MICE_sima_o3 l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_MICE_sima_wdr l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_MICE_sima_rainf l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_MICE_sima_pm10 l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_MICE_sima_nox l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_MICE_sima_prs l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_MICE_sima_so2 l13 ON l0.datetime = l13.datetime;

CREATE VIEW HDL_Project.sima_station_MVI_MICE_NTE2 AS 
Select l0.datetime, l0.CE as co, l1.NTE2 as tout, l2.NTE2 as no, l3.NTE2 as sr, l4.NTE2 as no2, l5.NTE2 as pm25, l6.NTE2 as wsr, l7.NTE2 as o3, l8.NTE2 as wdr, l9.NTE2 as rainf, l10.NTE2 as pm10, l11.NTE2 as nox, l12.NTE2 as prs, l13.NTE2 as so2
from HDL_Project.MVI_MICE_sima_rh l0  left join HDL_Project.MVI_MICE_sima_tout l1 ON l0.datetime = l1.datetime left join HDL_Project.MVI_MICE_sima_no l2 ON l0.datetime = l2.datetime left join HDL_Project.MVI_MICE_sima_sr l3 ON l0.datetime = l3.datetime left join HDL_Project.MVI_MICE_sima_no2 l4 ON l0.datetime = l4.datetime left join HDL_Project.MVI_MICE_sima_pm25 l5 ON l0.datetime = l5.datetime left join HDL_Project.MVI_MICE_sima_wsr l6 ON l0.datetime = l6.datetime left join HDL_Project.MVI_MICE_sima_o3 l7 ON l0.datetime = l7.datetime left join HDL_Project.MVI_MICE_sima_wdr l8 ON l0.datetime = l8.datetime left join HDL_Project.MVI_MICE_sima_rainf l9 ON l0.datetime = l9.datetime left join HDL_Project.MVI_MICE_sima_pm10 l10 ON l0.datetime = l10.datetime left join HDL_Project.MVI_MICE_sima_nox l11 ON l0.datetime = l11.datetime left join HDL_Project.MVI_MICE_sima_prs l12 ON l0.datetime = l12.datetime left join HDL_Project.MVI_MICE_sima_so2 l13 ON l0.datetime = l13.datetime;

